name: like_tube
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.1.2
  flutter:
    sdk: flutter
  flutter_modular: ^5.0.3
  flutter_triple: ^1.2.5
  fpdart: ^0.6.0
  lint: ^2.1.2
  mocktail: ^0.3.0
  modular_triple_bind: ^1.0.0
  path_provider: ^2.0.8
  path_provider_platform_interface: ^2.0.6
  plugin_platform_interface: ^2.1.4
  shared_preferences: ^2.1.2
  youtube_player_flutter: ^8.0.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  modular_test: ^2.0.0
  triple_test: ^1.0.0+1

flutter:
  uses-material-design: true
