name: like_tube
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  flutter:
    sdk: flutter
  flutter_modular: ^4.2.0
  flutter_triple: ^1.2.5
  fpdart: ^0.0.12
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  lint: ^1.8.1
  mocktail: ^0.1.4
  path_provider: ^2.0.8
  youtube_player_flutter: ^8.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  modular_test: ^1.0.1+1
  triple_test: ^0.0.8

flutter:
  uses-material-design: true