name: Dart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  JAVA_VERSION: "18.x"
  FLUTTER_CHANNEL: "stable"
  FLUTTER_KEYS_PATH: "./keys.json"
  PROPERTIES_PATH: "./android/key.properties"

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{env.JAVA_VERSION}}
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{env.FLUTTER_CHANNEL}}
      - run: flutter clean
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test

  build_ios:
    name: Build Flutter (iOS)
    needs: [flutter_test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{env.JAVA_VERSION}}
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{env.FLUTTER_CHANNEL}}
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign

  build_appbundle:
    name: Build Flutter (Android)
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{env.JAVA_VERSION}}
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{env.FLUTTER_CHANNEL}}
      - run: |
          echo flutter.targetSdkVersion=\${{ secrets.TARGET_SDK_VERSION }} >> ${{env.PROPERTIES_PATH}}

          echo { >> ${{ env.FLUTTER_KEYS_PATH }}
          echo \"YOUTUBE_APYKEY\"=\"\${{ secrets.YOUTUBE_APYKEY }}\" >> ${{ env.FLUTTER_KEYS_PATH }}
          echo } >> ${{ env.FLUTTER_KEYS_PATH }}
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build appbundle --release --dart-define-from-file=${{ env.FLUTTER_KEYS_PATH }}
        
      - name: Upload artifact 
        uses: actions/upload-artifact@v2
        with:
          name: appbundle
          path: build/app/outputs/bundle/release
